name: soul errors errors.soulpatch (x64)

on:
  push:
   branches:
    - master

env:
  SOUL_VER: 1.0.82

jobs:
  main:
    name: main
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest, macos-11, ubuntu-latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get SOUL compiler and Test (win)
        if: matrix.os == 'windows-latest'
        run: |
          powershell -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest https://github.com/soul-lang/SOUL/releases/download/${{env.SOUL_VER}}/binaries-windows-x64.zip -OutFile SOUL.zip"
          powershell -Command "Expand-Archive SOUL.zip -DestinationPath ."
          for %%f in (*.ext) do (
              if "%%~xf"==".ext" echo %%f
          )
          .\windows\x64\soul.exe errors tests\errors.soulpatch
          if %ERRORLEVEL% neq 0 exit /b %ERRORLEVEL%
        shell: cmd

      - name: Get SOUL compiler and Test (mac)
        if: matrix.os == 'macos-11'
        run: |
          curl -L "https://github.com/soul-lang/SOUL/releases/download/${{env.SOUL_VER}}/binaries-osx-x64.zip" -o SOUL.zip
          unzip SOUL
          ./osx/x64/soul errors tests/errors.soulpatch || exit 1
        shell: bash

      - name: Get SOUL compiler and Test (linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          curl -L "https://github.com/soul-lang/SOUL/releases/download/${{env.SOUL_VER}}/binaries-linux-combined.zip" -o SOUL.zip
          unzip SOUL
          ./linux/x64/soul errors tests/errors.soulpatch || exit 1
        shell: bash